import {PartnerPropertyFormType} from '../schema/PartnerPropertyFormSchema';

export const initialFormState: PartnerPropertyFormType = {
  propertyType: null,
  city: null,
  propertyFor: null,
  sellerType: null,
  location: null,
  zipCode: null,
  propertyName: null,
  price: null,
  imageURL: null,
  alarmSystem: null,
  videoURL: 'https://youtu.be/YZWhTCO-0-g',
  shortDescription: null,
  longDescription: null,
  readyToMove: null,
  bhkType: null,
  propertyForType: null,
  area: null,
  furnishing: null,
  boundaryWall: null,
  isFeatured: null,
  floor: null,
  lmUnit: null,
  openSide: null,
  parking: null,
  facing: null,
  constructionDone: null,
  ceilingHeight: null,
  gatedSecurity: null,
  lifts: null,
  propertyAge: null,
  surveillanceCameras: null,
  pantry: null,
  tags: null,
};
