export const propertyTypeFieldMappings = {
  CoWorking: [
    'propertyForType',
    'readyToMove',
    'lifts',
    'pantry',
    'floor',
    'furnishing',
    'parking',
    'facing',
  ],
  FOCP: [
    'propertyForType',
    'lifts',
    'bhkType',
    'floor',
    'furnishing',
    'parking',
    'facing',
  ],
  'Farm House': [
    'propertyAge',
    'gatedSecurity',
    'surveillanceCameras',
    'alarmSystem',
    'furnishing',
    'parking',
    'facing',
  ],
  Flat: [
    'propertyForType',
    'readyToMove',
    'lifts',
    'bhkType',
    'floor',
    'furnishing',
    'parking',
    'facing',
  ],
  'Independent House': [
    'propertyForType',
    'readyToMove',
    'lifts',
    'bhkType',
    'floor',
    'furnishing',
    'parking',
    'facing',
  ],
  Office: [
    'propertyForType',
    'readyToMove',
    'lifts',
    'pantry',
    'floor',
    'furnishing',
    'parking',
    'facing',
  ],
  'PG/Hostel': [
    'propertyForType',
    'readyToMove',
    'lifts',
    'bhkType',
    'floor',
    'furnishing',
    'parking',
    'facing',
  ],
  Plot: [
    'propertyForType',
    'constructionDone',
    'boundaryWall',
    'openSide',
    'facing',
  ],
  'Retail Shop': [
    'propertyForType',
    'readyToMove',
    'lifts',
    'ceilingHeight',
    'floor',
    'propertyAge',
    'gatedSecurity',
    'surveillanceCameras',
    'alarmSystem',
    'parking',
    'facing',
  ],
  Shop: [
    'propertyForType',
    'readyToMove',
    'lifts',
    'ceilingHeight',
    'floor',
    'propertyAge',
    'gatedSecurity',
    'surveillanceCameras',
    'alarmSystem',
    'parking',
    'facing',
  ],
  Villa: [
    'propertyAge',
    'gatedSecurity',
    'surveillanceCameras',
    'alarmSystem',
    'parking',
    'facing',
  ],
  Warehouse: [
    'propertyAge',
    'gatedSecurity',
    'surveillanceCameras',
    'alarmSystem',
  ],
  Others: [
    'propertyAge',
    'gatedSecurity',
    'surveillanceCameras',
    'alarmSystem',
  ],
};
